name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint || echo "Linting failed but continuing"
      
      - name: Type check
        run: npm run typecheck || echo "Type checking failed but continuing"
      
      - name: Run tests
        run: npm test || echo "Tests failed but continuing"
      
      - name: Generate WebP images
        run: node scripts/convert-to-webp.js
      
      - name: Generate OpenGraph images
        run: node scripts/generate-og-image.js
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist
          retention-days: 7
